- sms-core/src/main/kotlin/team/msg/sms/common/service/SecurityService.kt
- sms-core/src/main/kotlin/team/msg/sms/common/service/impl/SecurityServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/common/spi/SecurityPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/auth/service/AuthService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/auth/service/CommandAuthService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/auth/service/GetAuthService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/auth/service/impl/CommandAuthServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/auth/service/impl/GetAuthServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/auth/spi/CommandRefreshTokenPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/LogoutUseCase.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityAdapter.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/auth/RefreshTokenPersistenceAdapter.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/auth/AuthWebAdapter.kt
AuthApdater의 매핑추가 및 Security 연결, 
리프레시토큰을 삭제하는 함수 생성, 
AuthService에서 Port 하기위해 AuthService를 생성, 
현재 로그인한 유저의 id값을 가져오는 기능 구현
음... deleteById는 동작하지 않아 delete로 처리하였는데 이 방법은 해결법을 계속해서 찾아봐야 할거 같습니다.
서버주소/auth 주소에 Delete 메소드로 header에 Authorization 부분엔 Bearer를 붙인 AccessToken을 Refresh-Token 부분엔 Bearer를 붙이지 않은 RefreshToken을 보내게 되면 
성공시 200
실패시 
리프레시 토큰이 없을 경우 - 404 리프레시 토큰을 찾지 못함
요청보낸 유저 아이디값과 저장된 리프레시토큰의 유저의 아이디값이 다를 경우 - 404 유저를 찾지 못함
의 에러가 발생합니다
> 🔀 :: 19 - 로그아웃 기능을 구현하였습니다.

- sms-core/src/main/kotlin/team/msg/sms/common/util/FileUtil.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/file/usecase/UploadFileUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/file/usecase/UploadImageUseCase.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/file/FileWebAdapter.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/file/dto/res/UploadImageResponse.kt
이미지 업로드 기능을 구현하였습니다.
jpg, jpeg, png, heic 파일이 아니면 에러가 나도록 했습니다.
> 🔀 :: 27 - 이미지 업로드 기능 구현

- sms-infrastructure/src/main/kotlin/team/msg/sms/global/config/PropertiesScanConfig.kt
PropertiesScan 범위를 BasePackageClasses 로 변경
BasePackageClasses 에다가 ConfigurationProperties 어노테이션 붙은 패키지만 검사하게 범위를 좁힘
> PropertiesScan 범위를 BasePackageClasses 로 변경

- sms-core/src/main/kotlin/team/msg/sms/domain/auth/dto/response/SignInResponse.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/CookieJwtFilter.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/auth/AuthWebAdapter.kt
로그인시 토큰을 cookie로도 받을 수 있도록 추가하였습니다
로그아웃시 토큰과 헤더의 차이를 두었습니다
> 🔀 :: 63 - 로그인과 로그아웃 쿠키 추가

- sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/FindAllUseCase.kt
page 500 에러 해결
page 값이 0일 때 500 나게 변경 후 
page 값이 1일 때 성공 + page 값이 늘어나도 데이터가 없을 시 빈배열 데이터 전송
> 🔀 :: page 500 에러 해결

- sms-core/src/main/kotlin/team/msg/sms/domain/certificate/service/CommandCertificateService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/certificate/service/impl/CommandCertificateServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/certificate/spi/CommandCertificatePort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/languagecertificate/service/CommandLanguageCertificateService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/languagecertificate/service/impl/CommandLanguageCertificateServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/languagecertificate/spi/CommandLanguageCertificatePort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/prize/service/PrizeService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/region/service/CommandRegionService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/region/service/impl/CommandRegionServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/region/spi/CommandRegionPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/certificate/CertificatePersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/image/ImagePersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/languagecertificate/LanguageCertificatePersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/prize/PrizePersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/project/ProjectLinkPersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/region/RegionPersistenceAdapter.kt
코드 저장부분을 함수화 하였습니다
+
빈 리스트가 올때 500에러가 나는 부분을 수정하였습니다
기존 저장 할때 학생과 유저를 같이 보내야했던 부분을 삭제 하였습니다
> 🔀 :: 178 - 정보기입 부분 리팩토링 및 500 해결

- sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/req/SignUpRequestData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/SignUpWebRequest.kt
정보기입 시 이제 
region -> regions,
certificate -> certificates
languageCertificate -> languageCertificates
로 변경하셔야 합니다
> 🔀 :: 189 - 현재 DTO 네이밍 일치

- sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/FilterConfig.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/JwtFilter.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
쿠키 filter 에 인가 기능 제거
기존 회원가입 전 
기존 회원가입을 진행하지 않은 유저를 검사하여 다른 url 로 요청을 보내면 302를 보내주는 로직을 제거 하였습니다.
> 🔀 :: 쿠키 filter 에 인가 기능 제거

- sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/ModifyStudentInfoUseCase.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/thirdparty/aws/stroage/AwsS3Adapter.kt
이미지를 수정하는 곳에서 삭제할 때 project id 를 못찾아 오류가 났었습니다.
project id 값을 가진 project 를 copy 하여 데이터를 전송해주어 오류를 해결했습니다.
+ 추가로 이미지가 한글 이름일 경우 DB에 데이터 최대길이가 255로 책정되어 too long 오류가 발생하여 이를 UUID 값으로 설정하여 저희가 길이를 관리할 수 있게 변경하였습니다.
> 🔀 :: image delete error

- sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/SignInUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/major/service/impl/GetMajorServiceImpl.kt
``` kt
fun execute(request: SignInRequestData): SignInResponseData {
try {
val gAuthToken = gAuthPort.receiveGAuthToken(request.code)
val gAuthUserInfo = gAuthPort.receiveUserInfo(gAuthToken.accessToken)
val role = userService.getRoleByGAuthInfo(gAuthUserInfo.email, gAuthUserInfo.role)
val isExistsUser = userService.checkUserExistByEmail(gAuthUserInfo.email)
val user = userService.createUserWhenNotExistUser(
isExistsUser,
User(
name = gAuthUserInfo.name,
email = gAuthUserInfo.email,
stuNum = getStuNumValid(role, gAuthUserInfo),
roles = mutableListOf(role)
)
)
val (accessToken, accessTokenExp, refreshToken, refreshTokenExp) = jwtPort.receiveToken(user.id, role)
refreshTokenPort.saveRefreshToken(RefreshToken(refreshToken, user.id))
val isStudent = studentService.checkNewStudent(user, …
```
> 🔀 :: 160 - try catch로 처리되어 있던 gAuth 로그인 로직을 runCathing으로 변경하였습니다

- sms-core/src/main/kotlin/team/msg/sms/domain/certificate/service/CommandCertificateService.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/certificate/CertificatePersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/languagecertificate/LanguageCertificatePersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/prize/PrizePersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/project/ProjectPersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/region/RegionPersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/StudentTechStackPersistenceAdapter.kt
deleteAll 을 이용시 쿼리가 여러개 나가는 문제가 있어서 수정하였습니다.  
기존 deleteAll 함수를 QueryDSL을 이용하여 
사용하여.
쿼리를 줄였습니다
기존 걸리던 시간이 600~700ms에서 90 ~ 100초반 까지 개선 되었습니다 (로컬기준)
> 🔀 :: 233 - 회원탈퇴 부분 쿼리 여러개 나가던 이슈 해결

- sms-persistence/src/main/kotlin/team/msg/sms/global/config/RedisConfig.kt
Redis의 TTL 적용 오류를 수정했습니다.
https://wildeveloperetrain.tistory.com/273
위 글을 참고했습니다.
- Redis config에 @EnableRedisRepositories 추가
- EnableKeyspaceEvents.ON_STARTUP 옵션 부여
keyspace event 적용 전과 후의 저장 방식이 다른데, 그러면 이전에 있던 데이터에는 적용이 안되지 않을까요? 잔존하는 데이터들은 어떻게 하는 게 좋을까요?
> 🔀 250 :: Redis TTL 적용 오류 수정

- sms-core/src/main/kotlin/team/msg/sms/domain/auth/model/Role.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/entity/HomeroomTeacherJpaEntity.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/entity/TeacherJpaEntity.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/repository/HomeroomTeacherJpaRepository.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/repository/TeacherJpaRepository.kt
- 선생님 회원가입을 위해 선생님 엔티티와 권한을 추가했습니다.
선생님 엔티티와 담임 선생님 엔티티를 생성했습니다.
- 담임선생님 엔티티의 id는 노출될 일이 없기 때문에 UUID가 아닌 Long 타입으로 설정해주었습니다.
- 페이지 별 권한을 문자열로 작성하던 걸 상수로 변경해주었습니다.
> 선생님 회원가입을 위해 선생님 엔티티와 권한을 추가했습니다.

- sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/VerifyAccessUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/dto/req/SignUpHomeroomTeacherRequestData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/exception/HomeroomTeacherAlreadyException.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/exception/error/TeacherErrorCode.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/model/HomeroomTeacher.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/CheckHomeroomTeacherService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/CommandHomeroomTeacherService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/CommandTeacherService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/HomeroomTeacherService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/CheckHomeroomTeacherServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/CommandHomeroomTeacherServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/CommandTeacherServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/CommandHomeroomTeacherPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/HomeroomTeacherPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/QueryHomeroomTeacherPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpHomeroomTeacherUseCase.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/HomeroomTeacherPersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/entity/HomeroomTeacherJpaEntity.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/mapper/HomeroomTeacherMapper.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/repository/HomeroomTeacherJpaRepository.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/teacher/TeacherWebAdapter.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/teacher/dto/req/SignUpHomeroomTeacherWebRequest.kt
담임선생님으로 가입 api를 작성했습니다.
- HOMEROOM, 담임선생님 권한은 가지되 TEACHER, 선생님 권한도 가질 수 있도록 했습니다.
- 담임 중복 가입이 없도록 같은 학년, 반을 가지는 담임선생님의 회원가입을 막아두었습니다.
권한을 중복으로 가질 수 있으니 권한들을 "/" 문자로 나누어 반환하도록 변경했습니다.
3시간 동안 뭐가 문제지 하고 있었는디... 빌드 파일을 삭제하고 다시 빌드해보니 멀끔해진 오류창,... 덕분에 늦었습니다 😥
> 담임선생님으로 가입 api를 작성했습니다.

- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/CreateAuthenticationRequestData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/CreateAuthenticationResponseData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/event/AuthenticationHistoryEvent.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/handler/AuthenticationEventHandler.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/Authentication.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/AuthenticationHistory.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/AuthenticationService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/CommandAuthenticationService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/CommandAuthenticationServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/AuthenticationHistoryPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/AuthenticationPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/CommandAuthenticationHistoryPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/CommandAuthenticationPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/CreateAuthenticationUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/student/service/GetStudentService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/GetStudentServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/student/spi/QueryStudentPort.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationHistoryPersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationPersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/AuthenticationHistoryMapper.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/AuthenticationMapper.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationHistoryJpaRepository.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationJpaRepository.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/StudentPersistenceAdapter.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/req/CreateAuthenticationWebRequest.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/res/CreateAuthenticationWebResponse.kt
인증제 활동 생성 api를 작성했습니다.
- 인증제 활동을 생성하는 api를 작성했습니다.
- 이벤트 퍼블리셔를 사용해 히스토리를 저장하는 로직을 분리했습니다.
- student 객체를 찾는 함수 중 중복되는 함수명이 있어 변경해주었습니다.
- 추후 인증제 내용이 변경되는 일이 생기면 이벤트를 발행하면 됩니다.
> 인증제 활동 생성 api를 작성했습니다.

- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryAuthenticationDetailsResponseData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/AuthenticationNotFoundException.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/error/AuthenticationErrorCode.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/AuthenticationHistory.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/AuthenticationHistoryService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/AuthenticationService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetAuthenticationHistoryService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetAuthenticationService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetAuthenticationHistoryServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetAuthenticationServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/AuthenticationHistoryPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/AuthenticationPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryAuthenticationHistoryPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryAuthenticationPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationDetailsUseCase.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/config/JacksonConfiguration.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationHistoryPersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationPersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/AuthenticationHistoryJpaEntity.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/AuthenticationHistoryMapper.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationHistoryJpaRepository.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/res/QueryAuthenticationDetailsWebResponse.kt
인증제 활동 상세조회 api 를 작성했습니다.
- 인증제 활동 상세조회 api
- 최신 히스토리를 가져와 생성 날짜를 조회합니다.
- LocalDate 데이터포메터를 작성했습니다.
- 활동 히스토리에 생성일을 나타내는 createdAt을 추가했습니다.
> 인증제 활동 상세조회 api 를 작성했습니다.

- buildSrc/src/main/kotlin/DependencyVersions.kt
GAuth 버전을 2.0.0에서 3.0.0으로 변경했습니다.
Gauth 3.0.0
hotfix이므로 master 브랜치에 merge됩니다!
> Gauth 버전을 2.0.0 에서 3.0.0으로 변경했습니다.

- buildSrc/src/main/kotlin/DependencyVersions.kt
개발 서버 gauth 버전을 2.0.0에서 3.0.0으로 변경했습니다.
> update :: gauth 버전 2 -> 3

- sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/SignInUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/user/service/CommandUserService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/user/service/impl/CommandUserServiceImpl.kt
로그인 시 GAuth 학번과 다르면 업데이트
sms에 로그인 했을 때 GAuth의 학번과 서버에 저장된 학번이 다르면 정보를 업데이트할 수 있도록 로직을 추가했습니다.
졸업생도 stuNum이 빈 문자열로 저장되도록 변경했습니다.
> 로그인 시 GAuth 학번과 다르면 업데이트

- sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/CreateStudentLinkWebRequest.kt
학생정보 조회 링크 생성 API에서 최대로 지정할 수 있는 만료기간을 1 ~ 30일로 지정했습니다.
> 🔁 링크 최소 최대 만료기간 지정

- .github/workflows/sms_backend_develop_cd.yml
>
Resolves: #334 
원래 master-cd에서 develop까지 cd하려했는데 develop cd가 따로 있길래
develop cd사용할 수 있게끔 조건문 브랜치만 변경해줌
develop에 merge(push)가 많이 일어날 경우 ecr에 과거 버전 이미지가 쌓여서 비용이 지불될 수 있으니 주기적으로 지워줘야함
> chore: 조건문의 브랜치 변경

- sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/CreateStudentLinkWebRequest.kt
링크 token을 생성할 때 문자열 타입만 검증할 수 있는 @NotBlank를 UUID 타입과 Long 타입의 변수를 검증할 때 사용하여 문제가 발생했습니다.
Resolves: #342 
@NotBlank -> @NotNull 변경
> 기업이 조회할 수 있는 링크를 생성할 때 발생하는 500 예외를 고쳤습니다.

- sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/FindAllUseCase.kt
학생 리스트 조회 시 이전에 저장된 캐시가 남아있어 로그인 후에도 노** 와 같이 필터링 되거나, 로그아웃 후 이름이 그대로 노출되는 문제를 해결했습니다.
Resolves: #345 
캐싱 키에 Role 정보를 추가하여 Role 별로 조회 내용을 캐싱되도록 했습니다. 게스트와 학생, 선생님의 조회 결과를 각 Role에 맞게 되도록 변경했습니다!
테스트하는데 왜 자꾸 STUDENT로 Role이 들어오나 했는데 쿠키가....🤨 꺠닫는데 조금 걸려서 이 시간에 올려요
> 학생 리스트 조회 시 캐시 문제 해결

- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetGroupAuthenticationAreaService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetGroupAuthenticationAreaServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryGroupAuthenticationAreaPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationFormUseCase.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/GroupAuthenticationAreaPersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/GroupAuthenticationAreaRepository.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
인증제 폼 조회 시 UUID 키로 조회 하도록 변경하였습니다.
Resolves: #360 
tb_authentication 에서 가지는 UUID 키를 통해 조회 하여 추후 인증제를 선생님들이 여러개 만들어 확장하는데 있어 용이하도록 수정하였습니다.
- [노션](https://www.notion.so/matsougeum/7597d344e0d84245acb6c7fa5c7c4c12?pvs=4) 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g. `.env`, `노션`, `README`)
- [ ✅ ] 이 작업을 하고나서 공유해야할 팀원들에게 공유되었나요? (e.g. `"API 개발 완료됐어요"`, `"환경값 추가되었어요"`)
- [ ✅ ] 작업한 코드가 정상적으로 동작하나요?
- [ ✅ ] Merge 대상 브랜치가 올바른가요?
> 기존 인증제 폼 조회 -> 인증제 UUID로 인증제 정보를 조회하도록 변경

- sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/ModifyStudentPortfolioFileUseCase.kt
pdf 파일을 저장할 때 확장자를 저장하지 않은 문제를 해결했습니다.
https://asdf.sadf/asdf -> https://asdf.asdf/asdf.pdf
Resolves: #378
> 🔀 확장명을 포함해서 저장하기

- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
/student PUT에서 403 에러가 생긴다는 말을 들었고 코드를 확인해보니 /student PUT (학생정보 수정)에 대한 경로 접근 권한이 없는 것을 확인했습니다. + (이외에도 추가되지 않은 경로에 대한 권한을 추가하였습니다.)
Resolves: #380 
- SecurityConfig에 /student PUT 경로 권한 추가하기
- SecurityConfig에 /student/teacher/{uuid} GET 경로 권한 추가하기
> 🔀 학생정보 수정 API 접근 권한 추가

- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/StudentAuthenticationFormResponseData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/MarkingBoardNotFoundException.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/error/AuthenticationErrorCode.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/UserFormValue.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetMarkingBoardService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetUserFormValueService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetAuthenticationSectionServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetMarkingBoardServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetUserFormValueServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryAuthenticationSectionPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryMarkingBoardPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryUserFormValuePort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationFormUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryStudentAuthenticationFormDetailUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/SubmitUserFormDataUseCase.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationSectionPersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/MarkingBoardPersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/UserFormValuePersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/UserFormValueJpaEntity.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/UserFormValueRepository.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryStudentFormDetailWebResponse.kt
학생이 제출한 폼을 선생님이 조회할 수 있도록 개발했습니다.
Resolves: #377
1. userFormValue에 setId가 계획한대로 저장 되지 않던 부분 수정 + 예전엔 maxCount가 2이상인 상황에서만 추가하던 상황을 제거
2.학생 디테일 조회 기능 개발 + 첫 조회시 type을 채점 중으로 변경
3.기존 선생님이 만든 폼 조회할때 받던 uuid를 받지 않고 active 컬럼이 true인 폼을 조회할수 있도록 코드변경
ReadOnluUseCase를 사용하지 않은 이유는 채점 전에서 채점 중으로 변경하는 과정에서 update query가 발생하여 트랜잭션에 ReadOnly가 없는 UseCase로 작업하였습니다.
> 학생이 제출한 폼 상세 조회 기능 개발

- .github/workflows/sms_backend_master_cd.yml
code-deploy를 사용하지 않음으로 인한 CD 수정
- mater로 push가 되는 경우 기존 CD를 할때 진행되던 과정 + ssh 로 서버 접근 이후 docker compose restart 를 하는 로직을 추가하였습니다.
> 🔀 :: code-deploy를 사용하지 않음으로 인한 CD 스크립트 수정

- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/GradingRequestData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/UserFormValueNotFoundException.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/error/AuthenticationErrorCode.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/MarkingValue.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/CheckUserFormValueService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/CommandMarkingValueService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetMarkingValueService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/MarkingValueService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/UserFormValueService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/CheckUserFormValueServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/CommandMarkingServiceValueImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetMarkingValueServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/CommandMarkingValuePort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/MarkingValuePort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryMarkingValuePort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryUserFormValuePort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/GradingAuthenticationFormUseCase.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/MarkingValuePersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/UserFormValuePersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/MarkingValueJpaEntity.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/MarkingValueMapper.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/MarkingValueJpaRepository.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/GradingRequest.kt
학생이 제출한 폼을 채점하는 기능을 개발하였습니다.
Resolves: #386
markigValue 엔티티 수정 및 userFormValue의 setId로 검사하는 exists 함수 생성 
채점 저장 기능 개발 및 채점 완료 시 UNDER_RIVIEW로 상태 변경 및 totalScore 갱신 로직 추가
exist 함수를 queryDSL로 해서 더 개선 해볼수있을거 같으면 코드리뷰 부탁드립니다 ~
> 선생님 학생 채점 기능 개발

- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/CreateAuthenticationFieldRequestData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/AuthenticationSectionFieldResponseData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/AuthenticationField.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/CreateAuthenticationFormUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationFormUseCase.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/AuthenticationFieldJpaEntity.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/AuthenticationFieldMapper.kt
placeHolder의 표시가 placeholder이기에 변경 하였습니다
Resolves: #388 
폼을 생성할때 이제 placeHolder가 아닌 placeholder로 보내야함
폼을 조회할때 example이 아닌 placeholder로 받아야함
> placeHolder로 되어있던거 placeholder로 변경

- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/SubmitUserFormDataUseCase.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
지금 선생님이 만든 인증제 폼 리스트 조회 API가 존재하지 않아 클라이언트에서 하드코딩을 하던걸 param으로 수정합니다
Resolves: #395 
PathVariable 으로 받던 uuid를 Param으로 받게끔 변경합니다
> 학생 폼 제출할 때 재 활용성을 올립니다.

- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryAuthenticationVerifyResponseData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/MarkingBoard.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetMarkingBoardService.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetMarkingBoardServiceImpl.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryMarkingBoardPort.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/GradingAuthenticationFormUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationVerifyUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/SubmitUserFormDataUseCase.kt
- sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/MarkingBoardPersistenceAdapter.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/MarkingBoardJpaEntity.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/MarkingBoardMapper.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/queryDSL/MarkingBoardCustomRepository.kt
- sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/queryDSL/MarkingBoardRepositoryImpl.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryAuthenticationVerifyWebResponse.kt
학생이 인증제 버튼을 클릭하였을때마다 제출인지 아닌지 등등을 검사하는 기능을 추가 하였습니다.
Resolves: #399
markingBoard의 grader Name 컬럼 추가 및 인증제 검증 UseCase 개발
>
>
> 학생 인증제의 상태를 조회하는 API 개발

- sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherResponseData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTokenResponseData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/ModifyStudentInfoUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoTeacherUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoTokenUseCase.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailResponseData.kt
- sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryCurrentUserProfileDetailUseCase.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherWebResponse.kt
- sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTokenWebResponse.kt
현재 iOS, Android, Frontend 에서 portfolioUrl 필드가 Nullable처리에 대한 불명확한 이유로 인해, 현재로서는 필수값으로 바꾸면서 롤백을 진행하였습니다.
Resolves: #{이슈번호}
- portfolioUrl Nullable -> portfolioUrl required(true) 로 변경
- 기존 portfolioUrl 값을 -> portfolioUrl이나 portfolioFileUrl이 데이터 조회 해보고 없다면 빈 문자를 보내도록 수정
>
>
> portfolioUrl 필수값으로 응답하도록 수정

- sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationFormUseCase.kt
클라이언트에서 인증제 페이지에 들어갔을때 404가 뜨는 것을 확인했고,
서버를 확인해보니 인증제 폼이 없는 경우 500이 반환되고 있는 문제를 발견해서,
없는 경우 빈 배열을 반환하도록 수정했습니다.
Resolves: #412 
usecase의 반환값을 nullable로 변경하는 방법도 생각해봤지만 수정할 것이 많아질 것 같아서,
`runCatching` 함수를 이용해서 예외 처리하였습니다.
> 🔁 인증제 폼을 찾을 수 없는 경우, 빈 배열을 반환
