GSM-MSG/SMS-BackEnd

.github/workflows/sms_backend_ci.yml

CI 스크립트 작성
CI 스크립트를 작성하였습니다.
- .github/workflows 에 ci 스크립트 파일이 추가되었습니다.

:twisted_rightwards_arrows: CI 스크립트 작성

---

sms-core/src/main/kotlin/team/msg/sms/common/annotation/Aggregate.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/model/RefreshToken.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/model/Role.kt
sms-core/src/main/kotlin/team/msg/sms/domain/certificate/model/Certificate.kt
sms-core/src/main/kotlin/team/msg/sms/domain/gsmscore/model/GSMScore.kt
sms-core/src/main/kotlin/team/msg/sms/domain/region/model/Region.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/model/MilitaryService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/model/Student.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/model/WorkerType.kt
sms-core/src/main/kotlin/team/msg/sms/domain/techstack/model/TechStack.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/model/User.kt
sms-persistence/src/main/kotlin/team/msg/sms/global/config/RedisConfig.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/BaseIdEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/auth/entity/RefreshTokenEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/certificate/entity/CertificateJpaEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/gsmscore/entity/GSMScoreJpaEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/region/entity/RegionJpaEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/entity/StudentJpaEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/techstack/entity/TechStackJpaEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/user/entity/UserJpaEntity.kt

user
gsmscore
student
certificate
region
techstack
auth 식으로 도메인을 분류하였습니다

🔀 :: 4 - 필요한 모델들 생성 및 JPA에 등록시킬 엔티티 구현

---

sms-core/src/main/kotlin/team/msg/sms/domain/salary/model/Salary.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/salary/entity/SalaryJpaEntity.kt

전에 추가 안한 엔티티 추가
희망 연봉 엔티티 생성, 모델 생성

🔀 :: 11 - 희망연봉 엔티티 생성

---

build.gradle.kts
sms-core/build.gradle.kts
sms-core/src/main/kotlin/team/msg/sms/domain/student/exception/StudentNotFoundException.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/exception/error/StudentErrorCode.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/model/Student.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/spi/QueryStudentPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/service/GetUserServiceImpl.kt
sms-infrastructure/build.gradle.kts
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/FilterConfig.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/JwtFilter.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/exception/ExpiredTokenException.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/exception/InvalidRoleException.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/exception/InvalidTokenException.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/exception/UnexpectedTokenException.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/exception/error/SecurityErrorCode.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/principle/StudentDetail.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/principle/StudentDetailService.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/token/JwtParser.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/token/JwtProperties.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/StudentPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/entity/StudentJpaEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/mapper/StudentMapper.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/repository/StudentJpaRepository.kt
sms-presentation/build.gradle.kts

JwtFilter 구현
- JwtFilter 구현 및 config 로 따로 구현
- jitpack위치 전체 프로젝트로 변경

🔀 :: 10-JwtFilter 구현

---

buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
sms-persistence/build.gradle.kts

🔀 :: 16-Mariadb 의존성 추가

---

sms-core/src/main/kotlin/team/msg/sms/domain/auth/dto/response/ReIssueTokenResponse.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/dto/response/SignInResponse.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/exception/RefreshNotFoundException.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/exception/error/AuthErrorCode.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/spi/CommandRefreshTokenPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/spi/QueryRefreshTokenPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/spi/RefreshTokenPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/ReIssueTokenUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/exception/InternalServerErrorException.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/exception/error/UserErrorCode.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/service/GetUserService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/service/GetUserServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/spi/QueryUserPort.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/config/JacksonConfiguration.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/JwtFilter.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/token/GenerateJwtAdapter.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/token/JwtParser.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/auth/RefreshTokenPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/auth/repository/RefreshTokenRepository.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/user/UserPersistenceAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/auth/AuthWebAdapter.kt

🔀 :: 15-토큰 재발급 로직

---

sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/principle/StudentDetailService.kt

if(queryStudentPort.existsStudentById(studentId)) -> if(!queryStudentPort.existsStudentById(studentId))로
유저가 존재할때 에러가 아닌 유저가 존재하지 않을때 에러가 발생하도록 변경하였습니다

🔀 :: 21 - StudentDetailService의 조건문을 변경하였습니다

---

sms-core/src/main/kotlin/team/msg/sms/domain/major/dto/MajorsResponse.kt
sms-core/src/main/kotlin/team/msg/sms/domain/major/model/Major.kt
sms-core/src/main/kotlin/team/msg/sms/domain/major/service/MajorService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/major/service/QueryMajorService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/major/service/impl/QueryMajorServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/major/spi/MajorPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/major/spi/QueryMajorPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/major/usecase/QueryAllMajorUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/major/MajorPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/major/entity/MajorJpaEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/major/mapper/MajorMapper.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/major/repository/MajorJpaRepository.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/major/MajorWebAdapter.kt

🔀 :: 35 - Major 정보를 리스트로 반환하는 API 생성

---

sms-presentation/src/main/kotlin/team/msg/sms/common/WebMvcConfig.kt

🔀 :: 37 - CORS 설정

---

sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/SignInUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/request/SignUpData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/model/Student.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/model/User.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/entity/StudentJpaEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/mapper/StudentMapper.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/user/entity/UserJpaEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/user/mapper/UserMapper.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/SignUpWebRequest.kt

user 테이블에 stuNum 컬럼 생성
student에서 삭제
이에 맞춰 수정

 :: 39 - 학번 학생 기입에서 받는게 아닌 gAuth에서 받도록 수정

---

sms-core/src/main/kotlin/team/msg/sms/domain/file/exception/ImageInvalidExtensionException.kt
sms-core/src/main/kotlin/team/msg/sms/domain/file/usecase/UploadImageUseCase.kt

🔀 :: 42 - 이미지 업로드 문구 변경

---

sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-presentation/src/main/kotlin/team/msg/sms/common/WebMvcConfig.kt

SecurityConfig 변경 + allowCredentials true로 변경

🔀 :: 49 - CORS 에러 해결

---

sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/CookieJwtFilter.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/FilterConfig.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/JwtFilter.kt

쿠키로도 인가가 가능하게 변경
쿠키에 "Authorization" 키 가 붙은 Value 에 JWT 인증 토큰이 들어가 있다면 인가가 되어 사용가능하다

쿠키로도 인가가 가능하게 변경

---

sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt

🔀 permitAll -> authenticated로 변경

---

sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/CookieJwtFilter.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/JwtFilter.kt
sms-presentation/src/main/kotlin/team/msg/sms/common/extension/FileExtension.kt

convention 에 맞게 수정
convention 에 맞게 수정

🔀 :: convention 에 맞게 수정

---

sms-infrastructure/src/main/kotlin/team/msg/sms/global/error/GlobalExceptions.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/ExceptionFilter.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/CustomAccessDeniedHandler.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/CustomAuthenticationEntryPoint.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/exception/ForbiddenException.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/exception/error/SecurityErrorCode.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/token/JwtParser.kt

🔀 :: 55 - Custom Error 핸들링

---

sms-infrastructure/src/main/kotlin/team/msg/sms/SmsApplication.kt

🔀 :: 67 - 서버 실행할떄 타임존을 서울로 등록

---

sms-infrastructure/src/main/resources/application.yml

🔀 :: application.yml에 비어있던 부분 추가

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/service/GetStudentService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/GetStudentServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/spi/QueryStudentPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/dto/UserProfileResponse.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryCurrentUserProfileImgUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/StudentPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/repository/StudentJpaRepository.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/user/UserWebAdapter.kt

프로필 이미지를 가져오는 과정에서 학생이 아니라면 빈 문자열을 반환합니다.

🔀 :: 82 - 메인 페이지에서 로그인되어있는 유저의 프로필 이미지를 가져옵니다,

---

sms-core/src/main/kotlin/team/msg/sms/domain/auth/dto/response/SignInResponse.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/model/Role.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/SignInUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/CheckStudentServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/service/impl/GetUserServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryCurrentUserProfileImgUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/CookieJwtFilter.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/principle/StudentDetail.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/token/JwtParser.kt

🔀 :: 84 - 로그인 반환값에 ROLE 추가

---

sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/auth/AuthWebAdapter.kt

accessToken 유효한지 검사하는 로직
accessToken 유효한지 검사하는 로직 작성

🔀 accessToken 유효한지 검사하는 로직

---

sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/VerifyAccessUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/CheckStudentService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/CheckStudentServiceImpl.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/auth/AuthWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/auth/dto/VerifyAccessResponse.kt

🔀 :: 91 - 유효성 검사 API에 isExist 반환값 추가

---

sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/VerifyAccessUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/CheckStudentService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/GetStudentService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/CheckStudentServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/GetStudentServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoAnonymousUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoDetailUseCase.kt

🔀 :: 유효성 검사 리팩토링

---

sms-core/src/main/kotlin/team/msg/sms/domain/techstack/usecase/QueryAllTechStackUseCase.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/techstack/TechStackPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/techstack/repository/TechStackJpaRepository.kt

기존 Query에서 Distinct 처리를 데이터를 DB에서 가져온 후 Kotlin 내장 함수 distinct()를 사용하여 중복을 제거하였습니다.

🔀 :: 96 - 세부 스택이 필터가 동작안하는 버그를 수정하였습니다

---

.github/workflows/sms_backend_cd.yml

CD 스크립트 작성했습니다.
ECR로 업로드하는 과정까지만 우선 구현하였고, 다른 작업들을 마무리한 뒤에 나머지 스크립트를 작성할 듯 싶습니다.
CD 스크립트 작성했는데 지속적으로 테스트해봐야해서 계속 변경될 것 같습니다.

:sparkles: :: CD 스크립트 생성

---

.github/workflows/sms_backend_cd.yml
.github/workflows/sms_backend_ci.yml

CD 테스트를 위해서 지속적으로 열리는 PR 입니다.
CD 테스트를 위해 브랜치를 변경하였고 이 브랜치에서 테스트를 계속하다 Ok 되면 develop 브랜치로 변경 예정입니다.

:recycle: :: branches 변경

---

.github/workflows/sms_backend_cd.yml

메인에 박으면 깃플로우 꼬일까봐.. 귀찮더라도 pr 지속적으로 날리겠습니다..

:recycle: :: 스크립트 재구성

---

Dockerfile

백엔드의 도커 파일을 작성하였습니다.
제 나름대로 스프링 부트의 Docker 스크립트를 작성해봤습니다. 
백엔드 분들이 도커의 어느정도 지식이 있는걸로 알고 있기 때문에 제가 스크립트를 옳게 짰는지 확인해주시면 감사할 것 같습니다.

:sparkles: :: dockerfile 생성

---

Dockerfile

:pencil2: :: ENTRYPOINT 오타 수정

---

Dockerfile

:recycle: :: 버전 이슈로 스크립트 수정

---

Dockerfile

:recycle: :: 경로 수정

---

.github/workflows/sms_backend_cd.yml

:test_tube: : :: path test

---

.github/workflows/sms_backend_cd.yml

:recycle: :: delete CD - checkout

:recycle: :: delete CD - checkout

---

.github/workflows/sms_backend_cd.yml
.github/workflows/sms_backend_ci.yml

:recycle: :: CICD 통합

---

Dockerfile

 :recycle: :: 스크립트 변경

---

Dockerfile

:recycle: :: dockerfile 변경

---

Dockerfile

:rewind: :: 변경사항 롤백

---

Dockerfile

🐳 :: Dockerfile 수정

---

.github/workflows/sms_backend_cd.yml

:recycle: :: 스크립트 변경

---

.github/workflows/sms_backend_cd.yml

:bug: :: 스크립트 변수 수정

---

.github/workflows/sms_backend_cd.yml

:pencil2: :: 변수 오타 수정

---

.github/workflows/sms_backend_cd.yml

:pencil2: :: 오타 수정

---

sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/HealthCheckWebAdapter.kt

🔀 :: 121 - healthCheck 주소 추가

---

.github/workflows/sms_backend_cd.yml

ssh 관련 명령어를 추가하였습니다.
비용을 최대한 절약하기 위해서 cicd 관련된 파이프라인은 모두 git action 에서 처리하지 않을까 싶습니다.

:sparkles: :: ssh 관련 명령어 추가

---

.github/workflows/sms_backend_cd.yml

:recycle: :: ssh 접속하는 방식 변경

---

.gitignore
sms-infrastructure/src/main/kotlin/team/msg/sms/SmsApplication.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/ExceptionFilter.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/FilterConfig.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/JwtFilter.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/logger/LoggingScheduler.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/logger/filter/RequestLogFilter.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/thirdparty/aws/stroage/AwsS3Properties.kt
sms-infrastructure/src/main/resources/application.yml
sms-infrastructure/src/main/resources/logback-spring.xml

LogBack 로깅 시스템 구축하기
LogBack 로깅 시스템 구현
23시 59분 59초에 로깅 파일을 S3에 올리고 기존 로컬 파일을 삭제 한다.

LogBack 로깅 시스템 구축하기

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/CustomAccessDeniedHandler.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/CustomAuthenticationEntryPoint.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-infrastructure/src/main/resources/application.yml

security exception handler 401 <--> 403 처리 변경
AccessDeniedException 에서는 403 에러 처리로 변경하고
AuthenticationEntryPoint에서는 401 에러 처리로 변경했습니다.

security exception handler 401 <--> 403 처리 변경

---

.github/workflows/sms_backend_cd.yml

:recycle: :: codedeploy 스크립트 수정

:recycle: :: codedeploy 스크립트 수정

---

appspec.yml

:bug: :: 띄어쓰기 삭제

---

appspec.yml

:recycle: :: appspec.yml 변경

---

.github/workflows/sms_backend_cd.yml

:recycle: :: deploygroup name 변겨

:recycle: :: deploygroup name 변겨

---

appspec.yml

:recycle: :: source 변경

---

appspec.yml

:sparkles: :: permission 부여

---

appspec.yml

:poop: :: test 용으로 hooks 제거

---

appspec.yml

:recycle: :: 유저명 변경

---

appspec.yml

:recycle: :: timeout 시간 변경

---

sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/StudentPersistenceAdapter.kt

🔀 :: 146 - 탈퇴 요청시 학생정보가 없을때 예외처리

---

sms-core/src/main/kotlin/team/msg/sms/domain/auth/dto/response/VerifyAccessResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/VerifyAccessUseCase.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/auth/AuthWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/auth/dto/VerifyAccessResponse.kt

프론트에서 권한도 받아야 할것 같다고 하여 추가하였습니다

🔀 :: 148 - 유효성 검사 할때 role 권한 반환값 추가

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/spi/QueryStudentPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/repository/StudentJpaRepository.kt

회원가입 비관적 Lock 추가
회원가입 비관적 Lock 추가하여 회원가입 중복 방지 하기

🔀 :: 회원가입 비관적 Lock 추가

---

sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/repository/StudentJpaRepository.kt

Lock existsByUser
기존 Lock이 올바르지 않은 method 에 걸림

🔀 :: Lock existsByUser

---

sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/ReIssueTokenUseCase.kt
sms-presentation/src/main/kotlin/team/msg/sms/common/WebMvcConfig.kt

🔀 :: 리프레시토큰 재발급 수정

---

scripts/server_start.sh

:recycle: :: CD 스크립트 수정

---

sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/ReIssueTokenUseCase.kt

권한 404 에러로 변경
기존 500에러로 처리 되어져 있던 부분을 404 권한을 찾을 수 없는 에러로 처리 하기

🔀 :: 권한 404 에러로 변경

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/service/GetStudentService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/GetStudentServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/spi/QueryStudentPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileImgResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryCurrentUserProfileDetailUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryCurrentUserProfileImgUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/StudentPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/repository/StudentJpaRepository.kt
sms-presentation/src/main/kotlin/team/msg/sms/common/error/ValidErrorCode.kt
sms-presentation/src/main/kotlin/team/msg/sms/common/exception/InvalidUuidException.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/user/UserWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailWebResponse.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileWebResponse.kt

마이페이지에 필요한 API 생성
uuid 검사
uuid invalid 검사

🔀 :: 155 - 마이페이지에 필요한 API 생성 + uuid invalid 검사

---

.gitignore
sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/req/FiltersRequestData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/FilterStudentServiceImpl.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/FindAllFiltersWebRequest.kt

filter 요청 값 grade, classNum 배열 형식으로 변경
filter 에서 grade와 classNum을 다중 선택 할 수 있게 배열 형식으로 변경하였습니다.

🔀 :: 161 filter 요청 값 grade, classNum 배열 형식으로 변경

---

build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt

kotest depencies 추가
Kotest - Junit5 의존성 추가
Kotest - Assertions-core 의존성 추가
Kotest - Extension 의존성 추가

🔀 :: kotest depencies 추가

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/req/SignUpRequestData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoTeacherUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryCurrentUserProfileDetailUseCase.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/SignUpWebRequest.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/user/UserWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailWebResponse.kt

🔀 :: studentTechStack -> techStack으로 변경

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoAnonymousResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoAnonymousUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoDetailUseCase.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoAnonymousWebResponse.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoWebResponse.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/MainStudentsWebResponse.kt

🔀 :: 180 - 디테일 페이지에 상과 프로젝트 추가

---

sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherWebResponse.kt

studentTechStack 으로 되어있던 부분을 techStacks 로 변경하였습니다

🔀 :: 테크 스택 네이밍 수정

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt

score 저장하는 방식이 Name으로 되어 있어 변경
기존 score 가 저장이 되지 않아 
요청 데이터를 score 값에 매핑하게 변경

🔀 :: score 저장하는 방식이 Name으로 되어 있어 변경

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/MainStudentsResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/FindAllUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/techstack/dto/res/TechStacksResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/techstack/usecase/QueryAllTechStackUseCase.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/SignUpWebRequest.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/techstack/TechStackWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/techstack/dto/res/TechStacksWebResponse.kt

🔀 :: 전부 다 techStacks 로 변경

---

sms-persistence/src/main/kotlin/team/msg/sms/persistence/image/repository/ImageJpaRepository.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/prize/repository/PrizeJpaRepository.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/project/repository/ProjectJpaRepository.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/project/repository/ProjectLinkJpaRepository.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/project/repository/ProjectTechStackJpaRepository.kt

🔀 :: @Repository 어노테이션 추가

---

sms-presentation/src/main/kotlin/team/msg/sms/domain/auth/AuthWebAdapter.kt

🔀 :: 쿠키 관련 로직 주석처리

---

sms-core/src/main/kotlin/team/msg/sms/common/util/ProjectUtil.kt
sms-core/src/main/kotlin/team/msg/sms/domain/project/dto/res/ProjectResponseData.kt

🔀 :: 프로젝트 디테일 페이지에 icon 값 추가

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/service/CheckStudentService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/CheckStudentServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/ExistStudentUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryUserByUserIdUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/FilterConfig.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/JwtFilter.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt

존재하던 userPort와 studentPort에서 데이터베이스를 접근해야 하는데 infrastructure 영역에서 transaction 없이
데이터베이스에 접근하려다 보니 에러가 발생하여 UseCase로 변경하였습니다

🔀 :: 193 - JWT 필터 부분 UseCase 로 변경

---

sms-persistence/src/main/kotlin/team/msg/sms/persistence/techstack/TechStackPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/techstack/repository/TechStackJpaRepository.kt

parameter 값을 변경하지 않고 쿼리를 보낼때 value에 %값이 들어가도록 수정하였습니다

🔀 :: 테크스택 리스트 가져오기 부분 잘못된 쿼리 부분 수정

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/FilterStudentServiceImpl.kt

🔀 :: 필터 빈 리스트 보낼때 반환 안되는 이슈 해결

---

sms-presentation/src/main/kotlin/team/msg/sms/domain/auth/AuthWebAdapter.kt

cookie에 도메인을 제거 했습니다.
cookie에 존재하는 개발 서버 Domain을 제거 했습니다.

🔀 :: cookie에 도메인을 제거 했습니다.

---

sms-core/src/main/kotlin/team/msg/sms/domain/file/exception/ImageNotFoundException.kt
sms-core/src/main/kotlin/team/msg/sms/domain/file/exception/error/FileErrorCode.kt
sms-core/src/main/kotlin/team/msg/sms/domain/file/service/GetImageService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/file/service/impl/GetImageServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/file/spi/QueryImagePort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/project/service/CheckProjectService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/project/service/CommandProjectService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/project/service/impl/CheckProjectServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/project/service/impl/CommandProjectServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/project/spi/QueryProjectPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/ModifyStudentInfoUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/techstack/exception/TechStackNotFoundException.kt
sms-core/src/main/kotlin/team/msg/sms/domain/techstack/exception/error/TechStackErrorCode.kt
sms-core/src/main/kotlin/team/msg/sms/domain/techstack/service/CommandTechStackService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/techstack/service/GetTechStackService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/techstack/service/impl/CommandTechStackServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/techstack/service/impl/GetTechStackServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/techstack/spi/CommandTechStackPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/techstack/spi/QueryTechStackPort.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/image/ImagePersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/image/repository/ImageJpaRepository.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/project/ProjectLinkPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/project/ProjectPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/techstack/TechStackPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/techstack/repository/TechStackJpaRepository.kt

학생 정보 수정 API 리팩토링
학생 정보 수정에서 project 부분을 읽기 좋은 함수명과 변수명으로 변경 및 로직 개선 후 리팩토리 진행

🔀 :: Refac/modify student usecase

---

sms-core/src/main/kotlin/team/msg/sms/common/util/ProjectUtil.kt
sms-core/src/main/kotlin/team/msg/sms/domain/project/dto/res/ProjectLinkResponseData.kt

🔀 :: 프로젝트 링크 반환 id값 제거

---

sms-core/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryCurrentUserProfileDetailUseCase.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/user/UserWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailWebResponse.kt

profileImg -> profileImgUrl 로 명세에 맞게 수정
profileImg -> profileImgUrl 로 명세에 맞게 수정

🔀 :: profileImg -> profileImgUrl 로 명세에 맞게 수정

---

scripts/pullDocker.sh
scripts/server_start.sh

docker pull shell 변경
Infra쪽 리펙토링으로 인해 docker pull shell에 변동사항이 생겨 변경하였습니다.
docker pull ${REPO_URL} -> docker pull ${REPO_URL}/${ECR_REPOSITORY}:latest

🔀 :: docker pull shell 변경

---

docker-compose.yml
scripts/server_start.sh

- docker compose yml 작성
- server start script에 추가된 컨테이너 관련 명령줄 추가
docker compose에 redis, nginx 컨테이너 추가, bridge driver의 network추가
nginx image 구성
server start sh에 redis, nginx 실행 명령 추가, 생각해보니 이건 빼야할수도
server start sh 에 nginx 설정 파일 수정하는 명령줄 추가

🔀  :: 컨테이너 구축

---

appspec.yml

appspec 업데이트
권한 문제 등으로 sh이 실행되지 않는 것 같아 권한 관련으로 appspec.yml을 좀 수정해줬습니다.
appspec.yml permission 관련 변경

🔀 :: appspec 업데이트

---

appspec.yml
scripts/shell_start.sh

appspec.yml 변경
shell 자체를 찾아서 실행시키는 방식으로 변경하였습니다.
appspec.yml 내용 변경, shell 내용 변경

🔀 :: appspec.yml 변경

---

docker-compose.yml

entrypoint에서 command로 바꿈
entrypoint에서 command로 바꿈
entrypoint:
- service
- nginx
- start
==========
command: service nginx start

🔀  :: entrypoint에서 command로 바꿈

---

scripts/server_start.sh

nginx의 정상 실행을 위한 일부 로직 변경
nginx의 정상 실행을 위한 일부 로직 변경

🔀  :: nginx의 정상 실행을 위한 일부 로직 변경

---

scripts/server_start.sh

nginx reload 명령줄 제거
nginx reload 명령줄 제거

🔀  :: nginx reload 명령줄 제거

---

sms-core/src/main/kotlin/team/msg/sms/domain/major/service/impl/GetMajorServiceImpl.kt

🔀 :: Query -> Get으로 변경

---

docker-compose.yml

docker compose yml 수정
blue, green 서버에 awslogs driver이용해 cloudwatch로 로그 남게끔 구축
redis network에 추가

🔀  :: redis network에 추가, main server 로깅 구축

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/FilterStudentServiceImpl.kt

🔀 :: 현재 필터 부분에서 기타라는 부분이 서버에서는 검사하지 않아서 검사하도록 추가하였습니다

---

sms-presentation/src/main/kotlin/team/msg/sms/domain/auth/AuthWebAdapter.kt

기존 토큰 재발급에서 쿠키를 반환하지 않아서 에러가 나던 부분을 해결하였습니다

🔀 :: 토큰 재발급에서 쿠키 생성

---

.github/workflows/sms_backend_cd.yml

🔀  :: CD 시작 알림 추가

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoAnonymousResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoAnonymousUseCase.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoAnonymousWebResponse.kt

게스트 상태일때 contactEmail 추가
디테일 조회 부분에서 contactEmail 필드 값을 추가 했습니다.

🔀 :: 게스트 상태일때 contactEmail 추가

---

build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
sms-core/src/test/kotlin/team/msg/sms/domain/auth/core/usecase/GAuthSignInUseCaseTest.kt
sms-core/src/test/kotlin/team/msg/sms/global/annotation/SmsTest.kt

mock -> mockito로 변경 및 테스트 코드 작성

🔀 :: 로그인 테스트 코드 작성

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoDetailUseCase.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoWebResponse.kt

학생 디테일 페이지 부분 contactEmail 값 추가

🔀 :: 236 - 학생 디테일 페이지 이메일 추가

---

.github/workflows/sms_backend_deploy_feature_branch.yml

automate making test server
create yml

automate making test server

---

.github/workflows/sms_backend_deploy_feature_branch.yml

🔀 fix workflow

---

sms-persistence/src/main/kotlin/team/msg/sms/persistence/user/entity/UserJpaEntity.kt

FetchType 방식을 -> Lazy로 변경
기존 FetchType인 즉시로딩에서 지연로딩으로 변경

FetchType 방식을 -> Lazy로 변경

---

.github/workflows/deploy_feature/deploy_feature_server.sh
.github/workflows/deploy_feature/installDocker.json
.github/workflows/deploy_feature/runImages.json
.github/workflows/sms_backend_cd.yml
.github/workflows/sms_backend_deploy_feature_server.yml
.gitignore
docker-compose-feature.yml

feat branch의 배포를 자동화 하였습니다.
github action yml 작성
인스턴스의 라이프 사이클을 A-Z관리하는 쉘 스크립트 작성
feature 서버는 blue-green 배포를 하지 않기에 따로 docker compose yml 작성
인스턴스에 실행할 명령어 json 작성
github action탭에 들어가 sms_backend_deploy_feature_server 에서 배포하고 싶은 브랜치 선택후 run workflow 클릭
사실 yml을 작성하다가 aws id를 노출해버려 
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch 'file_path/file_name'" --prune-empty --tag-name-filter cat -- --all
명령어로 해당 파일들의 깃 히스토리를 삭제했는데 뭔가 자꾸 꼬이더라구요... 일단은 해결했는데 어디서 원래 되던게 안된다면 바로바로 알려주시면 감사하겠고 죄송합니다 ㅠ

테스트 서버 배포 자동화

---

.github/workflows/sms_backend_develop_cd.yml

develop branch용 cd 추가
develop branch용 cd 추가
sms_backend_develop_cd.yml 파일 추가했습니다

🔀 :: 255 - develop branch cd 추가

---

sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/SignInUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/VerifyAccessUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/CheckStudentService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/CheckStudentServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/exception/TeacherAlreadyException.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/exception/error/TeacherErrorCode.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/model/HomeroomTeacher.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/model/Teacher.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/CheckTeacherService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/CommandTeacherService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/TeacherService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/CheckTeacherServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/CommandTeacherServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/CommandTeacherPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/QueryTeacherPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/TeacherPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpTeacherUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/service/CheckUserService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/service/impl/CheckUserServiceImpl.kt
sms-core/src/test/kotlin/team/msg/sms/domain/auth/core/usecase/GAuthSignInUseCaseTest.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/TeacherPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/mapper/TeacherMapper.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/repository/TeacherJpaRepository.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/teacher/TeacherWebAdapter.kt

특별한 권한을 가지지 않는 일반 선생님으로 가입하는 api를 작성했습니다.
- 로그인 시 sms에 처음 접속한 teacher라면 isExist를 false로, 가입한 teacher라면 true로 반환하도록 했습니다.
- 일반 선생님으로 가입하는 로직을 작성했습니다.
- checkNewStudent 함수의 teacher 부분을 분리해 student만 검증하도록 했습니다.

일반 선생님으로 가입하는 api를 작성했습니다.

---

sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/CommandHomeroomTeacherService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/CommandTeacherService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/CommandHomeroomTeacherServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/CommandTeacherServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpDirectorTeacherUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpHomeroomTeacherUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpTeacherUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/service/CommandUserService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/service/impl/CommandUserServiceImpl.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/teacher/TeacherWebAdapter.kt

부장 선생님으로 가입하는 api를 작성했습니다.
- 부장 선생님으로 가입하는 usecase와 service를 작성했습니다.
- teacher service 로직을 리팩토링 했습니다.
- user service를 통해 user role을 저장할 수 있도록 했습니다.

부장 선생님으로 가입 api 작성

---

sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/CommandTeacherService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/CommandTeacherServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpDeputyPrincipalTeacherUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpPrincipalTeacherUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/teacher/TeacherWebAdapter.kt

- 교장 선생님으로 가입 api
- 교감 선생님으로 가입 api
- 딱히 다른 로직은 없어서 한꺼번에 작업했습니다.
- 교장 선생님으로 가입 api를 작성했습니다.
- 교감 선생님으로 가입 api를 작성했습니다.

교장 교감 선생님으로 가입 api 

---

sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/ActivityStatus.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/AuthenticationHistory.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/AuthenticationHistoryJpaEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/AuthenticationJpaEntity.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationHistoryJpaRepository.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationJpaRepository.kt

인증제 관련 엔티티 및 레포, 도메인 모델을 세팅했습니다.
- 인증제, 인증제 히스토리 엔티티 세팅
- 인증제, 인증제 히스토리 레포지토리 세팅
- 인증제, 인증제 히스토리 도메인 모델 세팅

인증제 관련 엔티티 및 레포, 도메인 모델 세팅

---

.github/workflows/sms_backend_cloudtype_develop_cd.yml
.github/workflows/sms_backend_develop_cd.yml
.github/workflows/sms_backend_master_cd.yml
appspec.yml
docker-compose-develop.yml
docker-compose.yml
scripts/pullDocker.sh
scripts/server_start.sh

개발 서버용 cd를 작성하였습니다
master cd 이미지 태그 추가
develop cd 작성
appspec.yml 파일 수정
develop-compose 파일 추가
cloudtype cd branch 작동 조건 변경
script 파일들 태그 변경

develop server cd 작성

---

sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryAuthenticationHistoriesResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryAuthenticationHistoryResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/InvalidGradeClassException.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/OnlyAccessMyselfException.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/PermissionRoleDeniedException.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/error/AuthenticationErrorCode.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetAuthenticationHistoryService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetAuthenticationHistoryServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryAuthenticationHistoryPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationHistoriesUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/GetHomeroomTeacherService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/GetTeacherService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/HomeroomTeacherService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/TeacherService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/GetHomeroomTeacherServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/GetTeacherServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/QueryHomeroomTeacherPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/QueryTeacherPort.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/config/JacksonConfiguration.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationHistoryPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationHistoryJpaRepository.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/HomeroomTeacherPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/TeacherPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/repository/HomeroomTeacherJpaRepository.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/repository/TeacherJpaRepository.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/res/QueryAuthenticationHistoriesWebResponse.kt

활동 히스토리 리스트를 조회하는 API를 개발했습니다.
- 활동 히스토리 리스트 조회 API 개발
- 시큐리티 접근 권한 역할 설정

활동 히스토리 리스트 조회 API 개발

---

sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryMyAuthenticationListResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/RequestMyAuthenticationResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetAuthenticationService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetAuthenticationServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryAuthenticationPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryMyAuthenticationUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationJpaRepository.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryMyAuthenticationListWebResponse.kt

나의 활동 리스트를 조회하는 API를 개발했습니다.
- 내 활동 리스트 조회 API 개발
- 시큐리티 접근 권한 역할 설정

나의 활동 리스트 조회 API 개발

---

sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryStudentAuthenticationListResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/RequestStudentAuthenticationResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryStudentAuthenticationUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryStudentAuthenticationListWebResponse.kt

학생의 활동 리스트를 조회하는 API를 개발하였습니다.
- 학생 활동 리스트 조회를 위한 API 개발
- Spring Security 권한 설정

학생 활동 리스트를 조회하는 API 개발

---

sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryRequestedAuthenticationDetailsResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryRequestedAuthenticationDetailsUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryRequestedAuthenticationDetailsWebResponse.kt

요청된 인증제 활동 상세조회 api를 작성했습니다.
- 요청된 인증제만 조회할 수 있도록 예외를 작성했습니다.
- 권한이 있는 선생님만 조회할 수 있도록 예외를 작성했습니다.
딱히 새로 작성해야하는 코드가 많지 않아 금방 끝나네요...

요청된 인증제 활동 상세조회 api를 작성했습니다.

---

sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/UpdateAuthenticationRequestData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/UpdateAuthenticationResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/UpdateAuthenticationUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/UpdateAuthenticationWebRequest.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/UpdateAuthenticationWebResponse.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/UpdateticationWebResponse.kt

인증제 활동 수정 api를 작성했습니다.
- 자신만 수정할 수 있도록 예외처리했습니다.
- 인증제 활동 상태가 인증됨 상태이거나 승인됨 상태일 시 수정할 수 없도록 예외처리했습니다.
- 수정 시 history를 저장합니다.

인증제 활동 수정 api를 작성했습니다.

---

sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/RejectAuthenticationRequestData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/ApproveRequestAuthenticationUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/RejectRequestAuthenticationUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/RejectAuthenticationWebRequest.kt

요청된 활동을 반려하는 API를 개발하였습니다.
- 요청된 활동 반려 API 개발
- Security 설정

요청된 활동 반려 API 개발

---

.github/workflows/sms_backend_cloudtype_develop_cd.yml
.github/workflows/sms_backend_develop_cd.yml

develop server를 aws에서 cloudtype으로 배포합니다
develop branch cd를 cloudtype cd 로 변경하였습니다
yml의 branch를 변경하였습니다

develop server를 cloudtype으로 배포

---

.github/workflows/sms_backend_master_cd.yml

cd workflow에 수동트리거 추가

---

.github/workflows/sms_backend_master_cd.yml

Reverts GSM-MSG/SMS-BackEnd#323
일단 취소

Revert "나중에 commit 이상하게 꼬이면 이 pr확인하세요"

---

.github/workflows/sms_backend_master_cd.yml

Reverts GSM-MSG/SMS-BackEnd#322
너도 취소 too

Revert "cd workflow에 수동트리거 추가"

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTokenResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/exception/StudentLinkNotFoundException.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/exception/error/StudentErrorCode.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/GetStudentLinkService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/StudentLinkService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/GetStudentLinkServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/spi/QueryStudentLinkPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoTokenUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/StudentLinkPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/repository/StudentLinkRepository.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTokenWebResponse.kt

token 링크를 클릭하면 기업이 학생 정보를 볼 수 있도록 API를 작성했습니다.
- 기업이 로그인을 하지 않아도 접근할 수 있도록 권한을 풀어놓았습니다.
- token으로 학생 정보를 찾아 열람합니다.

token 링크를 클릭하면 기업이 학생 정보를 볼 수 있도록 API를 작성했습니다.

---

sms-persistence/src/main/kotlin/team/msg/sms/persistence/user/entity/UserJpaEntity.kt

Reverts GSM-MSG/SMS-BackEnd#327

Revert "🔁 테이블 이름 users로 변경"

---

.github/workflows/sms_backend_master_cd.yml

마스터 브랜치로 병합

---

.github/workflows/sms_backend_develop_cd.yml

>
Resolves: #{이슈번호}
develop cd에서 메인서버 yml을 사용하고 있길래 테섭용 yml 시크릿을 생성함
>
>

chore: test yml이랑 main yml이랑 분리

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/req/ModifyStudentInfoRequestData.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/ModifyStudentInfoWebRequest.kt

포트폴리오 url 옵셔널처리
Resolves: #338 
>
>

포트폴리오 옵셔널처리

---

.github/workflows/sms_backend_develop_cd.yml
sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/req/ModifyStudentInfoRequestData.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/ModifyStudentInfoWebRequest.kt

master에 변경사항을 머지합니다.
포트폴리오 url을 옵셔널처리했습니다.
>
>

master에 변경사항 hotfix

---

.github/workflows/sms_backend_develop_cd.yml

fix: 오타 수정

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/FindAllUseCase.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/CreateStudentLinkWebRequest.kt

develop 변경사항을 master에 머지합니다!
- 학생 리스트 캐시 문재를 해결했습니다.

develop 변경사항을 master에 머지합니다!

---

sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/SignInUseCase.kt

> gAuth에서 학번이 0인 학생이 GAuth SDK에서 null로 오게되어 수정하였습니다
Resolves: #{351}
``` kt
private fun getStuNumValid(role: Role, gAuthUserInfo: GAuthUserInfo) =
if (role.name == "ROLE_STUDENT") {
val grade = gAuthUserInfo.grade ?: 0
val classNum = gAuthUserInfo.classNum ?: 0
val number = if (gAuthUserInfo.getNumber() == null) 0 else gAuthUserInfo.getNumber()
"$grade$classNum$number"
} else ""
private fun GAuthUserInfo.getNumber(): String {
val number = this.num ?: 0
return String.format("%02d", number)
}
``` 
로 로직을 변경하였습니다.
>
>
> 템플릿 …

student 학번 null인 계정 0으로 저장되도록 변경

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt

정보 기입 학번 0일시 추가

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt

2학년 4반 학생이 정보기입 할 때 AI과가 아닌 IoT과로 저장되는 문제가 있었습니다.
Resolves: #356 
3학년은 3, 4반이 IoT과로, 1, 2학년은 3반 IoT과, 4반 AI과로 저장되도록 변경했습니다.
필터 부분같이 학과가 쓰이는 부분은 다 확인했는데, 혹시 제가 변경해야 하는 데 놓친 부분이 있다면 알려주세요!

학과 결정 조건을 변경하였습니다.

---

sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/SubmitUserFormRequestData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/AuthenticationAreaFormResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/AuthenticationSectionFieldResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/AuthenticationSectionResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryAuthenticationFormResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationFormUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/SubmitUserFormDataUseCase.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/SubmitAuthenticationWebRequest.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryAuthenticationFormWebResponse.kt

인증제 폼 API 명세서를 클라이언트와 합의 하에 수정하게 되었습니다.
또한 수정 중 비즈니스 로직이 변경된 제출 부분이 바꼈습니다.
Resolves: 
>
>
- [ ✅ ] 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g. `.env`, `노션`, `README`)
- [ ✅ ] 이 작업을 하고나서 공유해야할 팀원들에게 공유되었나요? (e.g. `"API 개발 완료됐어요"`, `"환경값 추가되었어요"`)
- [ ✅ ] 작업한 코드가 정상적으로 동작하나요?
- [ ✅ ] Merge 대상 브랜치가 올바른가요?
- [ ✅ ] PR과 관련 없는 작업이 있지는 않나요?

인증제 DTO 수정 및 변경사항 UseCase에 적용

---

sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTokenResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/ModifyStudentInfoUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoTeacherUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoTokenUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailResponseData.kt
sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryCurrentUserProfileDetailUseCase.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTokenWebResponse.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/user/UserWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailWebResponse.kt

포트폴리오 업로드 기능이 URL과 PDF 파일로 나뉘면서 DTO 수정이 필요해졌습니다.
Resolves: #{365}
- 선생님용 학생정보 조회 API DTO 수정
- 기업 학생정보 열람 API DTO 수정
- 유저 마이페이지 API DTO 수정
- [] 이 작업을 하고나서 공유해야할 팀원들에게 공유되었나요? (e.g. `"API 개발 완료됐어요"`, `"환경값 추가되었어요"`)

포트폴리오 PDF 파일 관련 DTO 수정 및 "학생정보 수정 로직" 수정

---

sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt

SecurityConfig에 /student/pdf 경로에 접근 권한을 추가하였습니다.
Resolves: #372

:recycle: /student/pdf 경로 접근 권한 추가

---

sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherWebResponse.kt

선생님용 학생 디테일 조회 API에 portfolioFileUrl이 없습니다.
Resolves: #383

🔀 추가되지 않은 portfolioFileUrl 추가하기

---

sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationFieldPersistenceAdapter.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationFieldJpaRepository.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/queryDSL/AuthenticationSectionRepositoryImpl.kt

폼을 만들때 순서로 반환되지 않아 혼동이 오는걸 방지합니다.
Resolves: #390 
조회할때 orderBy 처리를 추가
>
>

section과 field를 조회할때 sort 컬럼을 오름차순 정렬 합니다

---

sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt

AccessToken 검증 요청이 실패한 이유를 찾아 해결합니다. denyAll로 변경되면서 403 접근 불가가 되어버렸습니다.
Resolves: #397 
오타를 수정합니다

SecurityConfig에 오타나있던걸 수정합니다

---

.github/workflows/sms_backend_master_cd.yml
sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationFormUseCase.kt

인증제 폼이 하나도 없는 경우의 예외를 처리하여 빈 배열을 반환하도록 하였습니다.

🔁 master 브랜치에 머지

---

buildSrc/src/main/kotlin/DependencyVersions.kt
sms-core/src/main/kotlin/team/msg/sms/common/spi/GAuthPort.kt
sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/SignInUseCase.kt
sms-core/src/test/kotlin/team/msg/sms/domain/auth/core/usecase/GAuthSignInUseCaseTest.kt
sms-infrastructure/src/main/kotlin/team/msg/sms/thirdparty/gauth/GAuthAdapter.kt

서버 URL 변경으로 GAuth SDK 버전이 변경되었습니다.

🔁 GAuth SDK 버전 수정

---

sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryStudentFormListUseCase.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/GetStudentService.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/GetStudentServiceImpl.kt
sms-core/src/main/kotlin/team/msg/sms/domain/student/spi/QueryStudentPort.kt
sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/StudentPersistenceAdapter.kt

요구사항 변경에 따라 인증제 목록은 각 담임 선생님 반의 인증제만 포함하게 되었습니다.
Resolves: #{300}

🔁 제출된 인증제 목록을 각 담임 선생님 반의 인증제만 반환하도록 함
